var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,d,b){a instanceof String&&(a=String(a));for(var e=a.length,g=0;g<e;g++){var h=a[g];if(d.call(b,h,g,a))return{i:g,v:h}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,b,e){if(d){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var g=a[e];g in b||(b[g]={});b=b[g]}a=a[a.length-1];e=b[a];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");var cp_loadingpage=cp_loadingpage||{};
(function(){var a=cp_loadingpage,d={threshold:100,effect:"show",effectspeed:0,codeblock:"",loadingScreen:!0,removeInOnLoad:!1,graphic:"bar",backgroundColor:"#000",foregroundColor:"#fff",text:!0,deepSearch:!1,modifyDisplayRule:0,pageEffect:"none",onComplete:function(){"undefined"!=typeof window.afterCompleteLoadingScreen&&window.afterCompleteLoadingScreen()}},b=[],e=0,g=!1,h=0;a.extend=function(a,c){for(var f in c)c.hasOwnProperty(f)&&(a[f]=c[f]);return a};a.validateScreenSize=function(){var f=a.options;
if(!("screen_size"in f&&"all"!=f.screen_size&&"screen_width"in f))return!0;var c=parseFloat(f.screen_width);if(isNaN(c)||!isFinite(c))return!0;var b=document.documentElement;b=window.innerWidth||b.clientWidth;return"greater"==f.screen_size&&c<=b||"lesser"==f.screen_size&&b<=c};a.imgLoaded=function(a){return a.complete&&0!==a.naturalHeight};a.displayBody=function(){jQuery("html").append("<style>body{"+(1*a.options.modifyDisplayRule?"display:block":"visibility:visible")+";}</style>")};a.loadOriginalImg=
function(){jQuery("body").find(".lp-lazy-load").each(function(){var a=jQuery(this),c=a.attr("data-src"),b=a.attr("data-srcset");a.removeClass("lp-lazy-load");"undefined"!=typeof c&&a.attr("src",c);"undefined"!=typeof b&&a.attr("srcset",c)})};a.graphicAction=function(f,b){if("graphic"in a.options&&"graphics"in a&&a.options.graphic in a.graphics&&a.graphics[a.options.graphic].created)a.graphics[a.options.graphic][f](b)};a.ApplyAnimationToElement=function(a){jQuery("body").addClass("lp-"+a)};a.onLoadComplete=
function(){var b="undefined"==typeof lp_close_btn&&"additionalSeconds"in a.options&&jQuery.isNumeric(a.options.additionalSeconds)?parseInt(a.options.additionalSeconds):0,c=function(){jQuery("#loading_page_codeBlock,.lp-close-screen").remove();a.graphicAction("complete",function(){a.ApplyAnimationToElement(a.options.pageEffect);a.options.onComplete();jQuery(document).trigger("loadingScreenCompleted")})};b?setTimeout(function(){c()},1E3*b):c()};a.setLoadImgEvents=function(){for(var f=jQuery(window).height(),
c=0,e=b.length;c<e;c++)if(!a.imgLoaded(b[c])){var d=jQuery(b[c]);if(a.options.deepSearch||d.offset().top<f)h++,d.on("load",function(){a.completeImageLoading()})}0==h&&this.completeImageLoading()};a.completeImageLoading=function(){e++;a.graphicAction("set",h?Math.min(e/h*100,100):100);h<=e&&!(1*a.options.removeInOnLoad)&&a.destroyLoader()};a.destroyLoader=function(){if(a.options.loadingScreen&&!g){a.displayBody();var b=Math.min(h?e/h*100:0,100),c=function(){a.graphicAction("set",b);if(100==b)a.onLoadComplete();
else b=Math.min(b+5,100),setTimeout(c,0)};g=!0;a.loadOriginalImg();c()}};a.loadingPage=function(){a.displayBody();b=jQuery("body").find("img:not(.lp-lazy-applied)");b.length&&a.setLoadImgEvents()};a.displayScreen=function(){jQuery(document).trigger("loadingScreenShow");if(a.options.closeBtn){var b=jQuery('<span class="lp-close-screen">X</span>');b.click(function(){lp_close_btn=!0;if(g)a.onLoadComplete();else a.destroyLoader()});jQuery("html").append(b)}a.options.codeblock&&a.options.codeblock.length&&
jQuery("html").append(a.options.codeblock);"undefined"!=typeof a.graphics&&"undefined"!=typeof a.graphics[a.options.graphic]&&(a.graphics[a.options.graphic].create(a.options),b=document.getElementById("loading_page_codeBlock"))&&(b.style.display="block")};a.options="undefined"!=typeof loading_page_settings?a.extend(d,loading_page_settings):d;a.options.text*=1;a.options.loadingScreen*=1;a.options.loadingScreen&&a.validateScreenSize()?a.displayScreen():(a.displayBody(),a.options.loadingScreen=0)})();
jQuery(function(){cp_loadingpage.options.loadingScreen&&cp_loadingpage.loadingPage()});jQuery(window).on("load",function(){cp_loadingpage.loadOriginalImg();cp_loadingpage.destroyLoader()});
